# Generated by Django 4.2.1 on 2023-07-22 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="images\\default.jpg", upload_to="images"),
        ),
    ]
